spring:
# 配置数据源信息
      datasource:
           url: jdbc:mysql://localhost:3306/yoi?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
           driver-class-name: com.mysql.cj.jdbc.Driver
           username: root
           password: 123456
           type: com.alibaba.druid.pool.DruidDataSource
      mvc:
        static-path-pattern: /**
        hidden-method:
          filter:
            enabled: true
      servlet:
          multipart:
            max-file-size: 40MB        # 设置单个文件最大大小为10MB
            max-request-size: 100MB
            enabled: true

      web:
        resources:
          static-locations: file:C:\Users\yo\Desktop\vuespringbootTotalProject\WebDevelopment\back\demo\src\main\resources\static\img,classpath:/static/img/,classpath:/public,classpath:/resources,classpath:/META-INF/resource


# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    global-config:
        db-config:
      # 配置MyBatis-Plus操作表的默认前缀
        table-prefix: t_
      # 配置MyBatis-Plus的主键策略
        id-type: auto
  type-aliases-package: com.entity
  #如果mapper接口与映射文件所在包地址不一致，可用这个指名xml映射文件所在地址
  mapper-locations: classpath*:com/mapper/*.xml
server:
  port: 8090
