spring:
  # 配置数据源信息
  datasource:
    url: jdbc:mysql://localhost:3306/yo?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    #开启驼峰命名匹配映射
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: assign_id
  type-aliases-package: com.yoi.entity
  #如果mapper接口与映射文件所在包地址不一致，可用这个指名xml映射文件所在地址
  mapper-locations: classpath:/mapper/*.xml